version: '3.8'

services:
  findxai:
    image: ghcr.io/taquangtu/findx:master
    env_file:
      - docker/findxai/.env
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 3
    depends_on:
      - findxai_db
      - redis
    restart: unless-stopped

  findxai_db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - 1298:5432
    environment:
      - POSTGRES_PASSWORD=longpassword
      - POSTGRES_USER=admin
      - POSTGRES_DB=findxai
  
  redis:
    image: redis:7.4.2

  findxai_mcp:
    build:
      context: .
      dockerfile: docker/findxai_mcp.dockerfile
    ports:
      - 8080:8080
    environment:
      - FINDXAI_GRPC_CONNECTION=findxai:50051
    restart: always
    depends_on:
      - findxai

