version: '3.8'

services:
  findxai_db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=longpassword
      - POSTGRES_USER=admin
      - POSTGRES_DB=findxai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d findxai"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  redis:
    image: redis:7.4.2
    
  findxai_db_migration:
    build:
      context: .
      dockerfile: docker/migration/dockerfile
    environment:
      - SQL_DIR=/app/sql
      - DB_URL=postgres://admin:longpassword@findxai_db:5432/findxai?sslmode=disable
      - RUN_MIGRATION=${RUN_MIGRATION}

      - API_KEY=<YOUR_API_KEY>
      - PROJECT_ID=<YOUR_PROJECT_ID>
    depends_on:
      findxai_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 3
    restart: "no"
  
  findxai:
    image: ghcr.io/xnoname79/findxai:latest
    env_file:
      - docker/findxai/.env
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 5s
      timeout: 2s
      retries: 3
    depends_on:
      findxai_db:
        condition: service_healthy
      findxai_db_migration:
        condition: service_healthy
    restart: unless-stopped
  
  tts:
    image: ghcr.io/xnoname79/tts:latest
    healthcheck:
      test: [
        "CMD",
        "python",
        "-c",
        "import urllib.request, sys; resp = urllib.request.urlopen('http://localhost:8080/health'); sys.exit(0 if resp.status == 200 else 1)"
      ]
      interval: 5s
      timeout: 2s
      retries: 3
    ports:
      - 8081:8080
    restart: unless-stopped
  
  findxai_mcp:
    build:
      context: .
      dockerfile: docker/findxai_mcp.dockerfile
    ports:
      - 8080:8080
    environment:
      - FINDXAI_GRPC_CONNECTION=findxai:50051
    restart: always
    depends_on:
      - findxai
      - tts
