# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import search_pb2 as search__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/google.search.v1.SearchService/Search',
                request_serializer=search__pb2.SearchRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeactivateKeys = channel.unary_unary(
                '/google.search.v1.SearchService/DeactivateKeys',
                request_serializer=search__pb2.DeactivateKeysRequest.SerializeToString,
                response_deserializer=search__pb2.DeactivateKeysResponse.FromString,
                _registered_method=True)
        self.ActivateKeys = channel.unary_unary(
                '/google.search.v1.SearchService/ActivateKeys',
                request_serializer=search__pb2.ActivateKeysRequest.SerializeToString,
                response_deserializer=search__pb2.ActivateKeysResponse.FromString,
                _registered_method=True)
        self.AddKeys = channel.unary_unary(
                '/google.search.v1.SearchService/AddKeys',
                request_serializer=search__pb2.AddKeysRequest.SerializeToString,
                response_deserializer=search__pb2.AddKeysResponse.FromString,
                _registered_method=True)
        self.GetKeys = channel.unary_unary(
                '/google.search.v1.SearchService/GetKeys',
                request_serializer=search__pb2.GetKeysRequest.SerializeToString,
                response_deserializer=search__pb2.GetKeysResponse.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=search__pb2.SearchRequest.FromString,
                    response_serializer=search__pb2.SearchResponse.SerializeToString,
            ),
            'DeactivateKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateKeys,
                    request_deserializer=search__pb2.DeactivateKeysRequest.FromString,
                    response_serializer=search__pb2.DeactivateKeysResponse.SerializeToString,
            ),
            'ActivateKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateKeys,
                    request_deserializer=search__pb2.ActivateKeysRequest.FromString,
                    response_serializer=search__pb2.ActivateKeysResponse.SerializeToString,
            ),
            'AddKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.AddKeys,
                    request_deserializer=search__pb2.AddKeysRequest.FromString,
                    response_serializer=search__pb2.AddKeysResponse.SerializeToString,
            ),
            'GetKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeys,
                    request_deserializer=search__pb2.GetKeysRequest.FromString,
                    response_serializer=search__pb2.GetKeysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.search.v1.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.search.v1.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.search.v1.SearchService/Search',
            search__pb2.SearchRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.search.v1.SearchService/DeactivateKeys',
            search__pb2.DeactivateKeysRequest.SerializeToString,
            search__pb2.DeactivateKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.search.v1.SearchService/ActivateKeys',
            search__pb2.ActivateKeysRequest.SerializeToString,
            search__pb2.ActivateKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.search.v1.SearchService/AddKeys',
            search__pb2.AddKeysRequest.SerializeToString,
            search__pb2.AddKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.search.v1.SearchService/GetKeys',
            search__pb2.GetKeysRequest.SerializeToString,
            search__pb2.GetKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
