FROM python:3.13-slim
WORKDIR /app

COPY src/projects/migration/pyproject.toml ./
COPY src/projects/migration/poetry.lock ./

RUN pip install poetry \
 && poetry config virtualenvs.create false \
 && poetry install --no-root

COPY src/projects/migration ./
COPY docker/migration/*.sql ./sql/

EXPOSE 8080
CMD ["python", "/app/main.py"]